// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgbjJ1PDTup7Njijzbdmw43S82h7LTwUo',
    appId: '1:749868810874:android:05fafe43afca00188731c3',
    messagingSenderId: '749868810874',
    projectId: 'enrutard-79ac9',
    storageBucket: 'enrutard-79ac9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu42b1Js6DyQ0AqIbAzAJP0naE8Kh2xyI',
    appId: '1:749868810874:ios:f17a0baae1c867418731c3',
    messagingSenderId: '749868810874',
    projectId: 'enrutard-79ac9',
    storageBucket: 'enrutard-79ac9.appspot.com',
    androidClientId: '749868810874-2bv4k8ibvv2dggrgsmmuvjvqk4fm7d96.apps.googleusercontent.com',
    iosClientId: '749868810874-1nf8ee5m5egsjsh3l2p0u4hismnrkih6.apps.googleusercontent.com',
    iosBundleId: 'com.enrutard.enrutafood',
  );
}
